### ISSUE TITLE
Tag releases with git tags / GitHub releases

### ISSUE THREAD

**Issue by serpi90** [smarr/SMark#1]
A baseline pointing to master is unstable, please tag versions with git tags or GitHub releases.

**Comment by smarr** [comment]
@theseion would you have the necessary information to do this?

**Comment by theseion** [comment]
Sure. I'll take care of it.

**Comment by theseion** [comment]
Done. I chose v1.0.4 as we did some minor changes after moving to Github and the previous version was 1.0.3.

**Comment by serpi90** [comment]
Thank you

**Comment by smarr** [comment]
Ah, simple solution. Perfect. Thank you!
