### ISSUE TITLE
Transcript logging on every image save

### ISSUE THREAD

**Issue by pavel-krivanek** [smarr/SMark#5]
The method `ScriptStarter class>>#startUp` in the `Scripting` package makes this: 

```smalltalk
	IsResuming ifFalse: [ Transcript show: 'ScriptStarter did not execute a given script, since it assumes to be executed after a snapshot and not during startup.'.
		^ self. ].
```

Which means that this class writes the text to Transcript on every normal image save. Moreover, it does not end it with `cr` which makes it even more annoying.

**Comment by smarr** [comment]
Sorry, all I can say is: PRs welcome :)
